-- MySQL Script generated by MySQL Workbench
-- Tue Aug 29 12:41:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema usando_hibernate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema usando_hibernate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `usando_hibernate` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `usando_hibernate` ;

-- -----------------------------------------------------
-- Table `usando_hibernate`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usando_hibernate`.`forum` (
  `IDFORUM` INT(11) NOT NULL,
  `ASSUNTO` VARCHAR(45) NOT NULL,
  `DESCRICAO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IDFORUM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usando_hibernate`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usando_hibernate`.`Usuario` (
  `idUSUARIO` INT(11) NOT NULL,
  `NOME` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `forum_IDFORUM` INT(11) NOT NULL,
  PRIMARY KEY (`idUSUARIO`),
  INDEX `fk_Usuario_forum_idx` (`forum_IDFORUM` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_forum`
    FOREIGN KEY (`forum_IDFORUM`)
    REFERENCES `usando_hibernate`.`forum` (`IDFORUM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
